In [162]:
import pandas as pd
import numpy as np

In [163]:
template_data = pd.read_csv('template_dataset_150_steps_from0to1_approx45000lines.csv')
template_data.head(n=3)

   Unnamed: 0         u         g         r         i         z  redshift
0           0  8.044391  6.575220  6.266480  5.602644  5.201868       0.0
1           1  8.065978  6.797687  6.284164  5.788807  5.435865       0.0
2           2  5.892363  3.422409  3.274510  2.507776  2.082993       0.0

In [184]:
measured_data = pd.read_csv('SDSSDR7-10-percent-err-limit-25000-line.csv')
measured_data['redshift'] = measured_data['z'] # rename column z to redshift (name mismatch)
measured_data['r'] = measured_data['m_r']
measured_data[['r', 'ug', 'gr','ri', 'iz', 'redshift' ]].head(n=3)

          r        ug        gr        ri        iz  redshift
0  17.47122  1.643725  0.849079  0.457232  0.345194  0.114218
1  17.04054  1.091037  0.359422  0.253422  0.152236  0.052989
2  17.78998  0.984486  0.320728  0.265356  0.085814  0.053157

#### In order to be able to use later on de column names for the Beck-method

In [185]:
template_data['ug'] = template_data['u'] - template_data['g']
template_data['gr'] = template_data['g'] - template_data['r']
template_data['ri'] = template_data['r'] - template_data['i']
template_data['iz'] = template_data['i'] - template_data['z']
template_data[['r', 'ug', 'gr','ri', 'iz', 'redshift' ]].head(n=3)

          r        ug        gr        ri        iz  redshift
0  6.266480  1.469171  0.308739  0.663837  0.400776       0.0
1  6.284164  1.268291  0.513523  0.495357  0.352942       0.0
2  3.274510  2.469954  0.147899  0.766734  0.424782       0.0

### Representation of the function that will do the template selection based on real world, measured data.

In [186]:
from sklearn.neighbors import NearestNeighbors

def find_nearest_template_in_measured_data(template_data, measured_data, indices):
    
    # NN algorithm
    neigh = NearestNeighbors(n_neighbors=1, algorithm='kd_tree', metric='l2')
    neigh.fit(template_data[indices].values)
    
    inds = neigh.kneighbors(measured_data[indices].values, return_distance=True)
    
    order = np.argsort(inds[0].flatten())
    
    N = 5000
    
    values = template_data[indices].values[inds[1].flatten()[order][:N], :].reshape(N, 5)
    
    df = pd.DataFrame(values)
    df.columns = indices
    
    return df

In [187]:
df = find_nearest_template_in_measured_data(template_data, measured_data, ['ug', 'gr', 'ri', 'iz', 'redshift'])

In [188]:
df

            ug        gr        ri        iz  redshift
0     0.443946  0.648641  0.398655  0.300423  0.268456
1     0.264497  0.744974  0.303576  0.360882  0.302013
2     0.264497  0.744974  0.303576  0.360882  0.369128
3     0.264497  0.744974  0.303576  0.360882  0.382550
4     0.327752  0.716212  0.335841  0.283164  0.382550
5     0.443946  0.648641  0.398655  0.300423  0.174497
6     0.488924  0.626155  0.418719  0.320732  0.201342
7     0.461399  0.638099  0.408723  0.307318  0.201342
8     1.268291  0.513523  0.495357  0.352942  0.046980
9     0.551566  0.596702  0.445021  0.318413  0.140940
10    0.246120  0.374337  0.201056  0.219027  0.429530
11    0.418706  0.655053  0.393719  0.296520  0.134228
12    0.246120  0.374337  0.201056  0.219027  0.248322
13    0.328333  0.213262  0.263032  0.209276  0.469799
14    0.327752  0.716212  0.335841  0.283164  0.315436
15    0.327752  0.716212  0.335841  0.283164  0.221477
16    0.418706  0.655053  0.393719  0.296520  0.362416
17    0.327752  0.716212  0.335841  0.283164  0.026846
18    0.327752  0.716212  0.335841  0.283164  0.248322
19    0.418706  0.655053  0.393719  0.296520  0.268456
20    1.268291  0.513523  0.495357  0.352942  0.093960
21    0.418706  0.655053  0.393719  0.296520  0.275168
22    0.192285  0.466341  0.216772  0.199478  0.275168
23    0.418706  0.655053  0.393719  0.296520  0.248322
24    0.264497  0.744974  0.303576  0.360882  0.268456
25    0.418706  0.655053  0.393719  0.296520  0.275168
26    0.418706  0.655053  0.393719  0.296520  0.194631
27    0.551566  0.596702  0.445021  0.318413  0.234899
28    0.192285  0.466341  0.216772  0.199478  0.248322
29    0.418706  0.655053  0.393719  0.296520  0.221477
...        ...       ...       ...       ...       ...
4970  1.268291  0.513523  0.495357  0.352942  0.127517
4971  0.761778  0.487348  0.541016  0.353343  0.181208
4972  1.268291  0.513523  0.495357  0.352942  0.161074
4973  1.268291  0.513523  0.495357  0.352942  0.127517
4974  1.268291  0.513523  0.495357  0.352942  0.053691
4975  1.268291  0.513523  0.495357  0.352942  0.087248
4976  1.268291  0.513523  0.495357  0.352942  0.053691
4977  0.761778  0.487348  0.541016  0.353343  0.053691
4978  1.268291  0.513523  0.495357  0.352942  0.073826
4979  0.480076  0.030448  0.237382  0.224771  0.040268
4980  0.761778  0.487348  0.541016  0.353343  0.120805
4981  1.268291  0.513523  0.495357  0.352942  0.046980
4982  1.268291  0.513523  0.495357  0.352942  0.107383
4983  1.268291  0.513523  0.495357  0.352942  0.080537
4984  1.268291  0.513523  0.495357  0.352942  0.073826
4985  0.519111 -0.025961  0.279250  0.197109  0.046980
4986  1.268291  0.513523  0.495357  0.352942  0.067114
4987  1.268291  0.513523  0.495357  0.352942  0.026846
4988  1.268291  0.513523  0.495357  0.352942  0.100671
4989  1.268291  0.513523  0.495357  0.352942  0.147651
4990  1.268291  0.513523  0.495357  0.352942  0.040268
4991  1.268291  0.513523  0.495357  0.352942  0.120805
4992  0.761778  0.487348  0.541016  0.353343  0.100671
4993  1.268291  0.513523  0.495357  0.352942  0.167785
4994  1.268291  0.513523  0.495357  0.352942  0.140940
4995  1.268291  0.513523  0.495357  0.352942  0.127517
4996  1.268291  0.513523  0.495357  0.352942  0.093960
4997  1.268291  0.513523  0.495357  0.352942  0.167785
4998  0.910995  0.412210  0.603545  0.376142  0.087248
4999  0.369936  0.675487  0.245689 -0.243211  0.201342

[5000 rows x 5 columns]

In [189]:
df.to_csv('dataframes/dataframe0.csv')